---
- name: Setup base platform
  hosts: localhost
  gather_facts: False
  vars:
    ec_name: web-sg
    ec_name_ssh: ssh-sg
    aws_region: us-east-2
    aws_tag: web
    aws_ssh_from: 219.98.69.0/24
  tasks:
    - name: Create security group rule for web(redash)
      ec2_group:
        name: "{{ ec_name }}"
        description: security group rule for web(redash)
        # vpc_id: vpc-xxxxxxxx
        # profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        tags:
          env: "{{ aws_tag }}"
        rules:
          - proto: tcp
            ports:
            - 80
            - 443
            # - 8888
            cidr_ip: "0.0.0.0/0"
            rule_desc: allow all on port 80, 443, 8888

    - name: Create security group rule for ssh
      ec2_group:
        name: "{{ ec_name_ssh }}"
        description: security group rule for ssh
        region: "{{ aws_region }}"
        tags:
          env: "{{ aws_tag }}"
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: "{{ aws_ssh_from }}"
            rule_desc: allow specific host on port 22
